version: '3.9'

services:
  db:
    build: ./DB
    container_name: nevers_postgis
    env_file: ./.env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DATA/clean:/import:ro
      - ./DB/init_db:/docker-entrypoint-initdb.d:ro
      - ./exports:/exports
      - ./SQL:/SQL
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build: ./app
    container_name: nevers_api
    env_file: ./.env
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:5000/api/test_db').status==200 else sys.exit(1)" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
